export const FETCH_ITEMS_START ="FETCH_ITEMS_START";
export const FETCH_ITEMS_SUCCESS= "FETCH_ITEMS_SUCCESS";
export const FETCH_ITEMS_FAIL ="FETCH_ITEMS_FAIL";

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const SUB_QUANTITY = 'SUB_QUANTITY';
export const ADD_QUANTITY = 'ADD_QUANTITY';

export const UPDATE_SORT = 'UPDATE_SORT';
export const UPDATE_SEARCH = 'UPDATE_SEARCH';
export const UPDATE_FILTER = 'UPDATE_FILTER';
